on:
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn
      - run: yarn build --pathprefix /toolshed/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: www
          publish_dir: _site
